//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParameterEditor.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class Celebrity
    {
        public int Id { get; set; }

        [DisplayName("First Name")]
        public string FirstName { get; set; }

          [DisplayName("Last Name")]
        public string LastName { get; set; }
        public int Age { get; set; }
        public string Profession { get; set; }
        public Nullable<int> Awards { get; set; }
    }
}
